#pragma once
#include "layout_core.h"
// clang-format off
#define FN60_ROW1  KC_ESC, F_ROW_BASE, KC_DEL,
#define FN60_ROW2  KC_TAB, QK_MACRO_6, QK_MACRO_4, QK_MACRO_2, QK_MACRO_0, DM_PLY1, KC_NO, DM_REC1, DM_REC2, DM_RSTP, KC_NO, QK_MACRO_10, QK_MACRO_8,
#define FN60_ROW3  KC_ESC, QK_MACRO_7, QK_MACRO_5, QK_MACRO_3, QK_MACRO_1, DM_PLY2, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_NO, QK_MACRO_11, QK_MACRO_9, KC_ENT,
#define FN60_ROW4  KC_LSFT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, RGB_MO, SYS_MO, KC_NO, KC_HOME, KC_PGDN, KC_PGUP, KC_RSFT,
// clang-format on

#define FN60_R5_LCTL KC_LCTL
#define FN60_R5_LALT KC_LALT
#define FN60_R5_SPACE SP_FN
#define FN60_R5_RALT KC_NO
#define FN60_R5_RCTL KC_RCTL
