#pragma once
#include "layout_core.h"
// clang-format off
// Ebene 1
#define NEOQWERTZ1_60_ROW1  KC_ESC, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, DE_SS, DE_EQL, KC_BSPC,
#define NEOQWERTZ1_60_ROW2  KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, DE_Z, KC_U, KC_I, KC_O, KC_P, DE_UDIA, DE_PLUS,
#define NEOQWERTZ1_60_ROW3  TD(TD_CAPS_NEO_LEAD), KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, DE_ODIA, DE_ADIA, TD(TD_NEO_L3MO_LEAD), KC_ENT,
#define NEOQWERTZ1_60_ROW4  NEO_SHIFT, L4_MO_NEO, DE_Y, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, DE_COMM, DE_DOT, DE_MINS, NEO_SHIFT,

// Ebene 2
#define NEOQWERTZ2_60_ROW1  KC_TRNS, DE_DEG, DE_SECT, UC(0x2113), UC(0x00BB), UC(0x00AB), DE_DLR, RALT(KC_E), UC(0x201E), UC(0x201C), UC(0x201D), UC(0x1E9E), DE_GRV, KC_BSPC,
#define NEOQWERTZ2_60_ROW2  KC_TRNS, S(KC_Q), S(KC_W), S(KC_E), S(KC_R), S(KC_T), S(DE_Z), S(KC_U), S(KC_I), S(KC_O), S(KC_P), S(DE_UDIA), DE_ASTR,
#define NEOQWERTZ2_60_ROW3  TD(TD_CAPS_NEO_LEAD), S(KC_A), S(KC_S), S(KC_D), S(KC_F), S(KC_G), S(KC_H), S(KC_J), S(KC_K), S(KC_L), S(DE_ODIA), S(DE_ADIA), TD(TD_NEO_L3MO_LEAD), S(KC_ENT),
#define NEOQWERTZ2_60_ROW4  KC_TRNS, L4_MO_NEO, S(DE_Y), S(KC_X), S(KC_C), S(KC_V), S(KC_B), S(KC_N), S(KC_M), DE_SCLN, DE_COLN, DE_UNDS, KC_TRNS,

// Ebene 3
#define NEOQWERTZ3_60_ROW1  UC(0x21BB), UC(0x00B9), UC(0x00B2), UC(0x00B3), UC(0x203A), UC(0x2039), UC(0x00A2), UC(0x00A5), UC(0x201A), UC(0x2018), UC(0x2019), DE_MINS, UC(0x00B7), KC_DEL,
#define NEOQWERTZ3_60_ROW2  KC_NO, DE_AT, DE_UNDS, DE_LBRC, DE_RBRC, DE_CIRC, DE_EXLM, DE_LABK, DE_RABK, DE_EQL, DE_AMPR, DE_DLR, DE_TILD,
#define NEOQWERTZ3_60_ROW3  TD(TD_CAPS_NEO_LEAD), DE_BSLS, DE_SLSH, DE_LCBR, DE_RCBR, DE_ASTR, DE_QUES, DE_LPRN, DE_RPRN, DE_MINS, DE_COLN, DE_AT, TD(TD_NEO_L3MO_LEAD), KC_ENT,
#define NEOQWERTZ3_60_ROW4  KC_LSFT, L4_MO_NEO, DE_HASH, DE_DLR, DE_PIPE, DE_TILD, DE_GRV, DE_PLUS, DE_PERC, DE_DQUO, DE_QUOT, DE_SCLN, KC_RSFT,

// Ebene 4
#define NEOQWERTZ4_60_ROW1  KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_SLSH, KC_ASTR, KC_MINS,
#define NEOQWERTZ4_60_ROW2  KC_TAB, KC_PGUP, KC_BSPC, KC_UP, KC_DEL, KC_PGDN, KC_DOWN, KC_P7, KC_P8, KC_P9, KC_PPLS, KC_PMNS, KC_ENT,
#define NEOQWERTZ4_60_ROW3  KC_HOME, KC_LEFT, KC_DOWN, KC_RGHT, KC_END, KC_INS, KC_P4, KC_P5, KC_P6, KC_COMM, KC_DOT, KC_NO, L4_MO_NEO, KC_ENT,
#define NEOQWERTZ4_60_ROW4  KC_LSFT, L4_MO_NEO, KC_ESC, KC_TAB, KC_INS, KC_ENT, LCTL(KC_Z), KC_P1, KC_P2, KC_P3, KC_NO, KC_NO, KC_RSFT,
// clang-format on

// Kern-ROW5 (5 Tasten) pro Ebene
#define NEOQWERTZ1_60_R5_LCTL KC_LCTL
#define NEOQWERTZ1_60_R5_LALT KC_LALT
#define NEOQWERTZ1_60_R5_SPACE SP_FN
#define NEOQWERTZ1_60_R5_RALT L4_MO_NEO
#define NEOQWERTZ1_60_R5_RCTL KC_RCTL

#define NEOQWERTZ2_60_R5_LCTL KC_LCTL
#define NEOQWERTZ2_60_R5_LALT KC_LALT
#define NEOQWERTZ2_60_R5_SPACE SP_FN
#define NEOQWERTZ2_60_R5_RALT L4_MO_NEO
#define NEOQWERTZ2_60_R5_RCTL KC_RCTL

#define NEOQWERTZ3_60_R5_LCTL KC_LCTL
#define NEOQWERTZ3_60_R5_LALT KC_LALT
#define NEOQWERTZ3_60_R5_SPACE SP_FN
#define NEOQWERTZ3_60_R5_RALT L4_MO_NEO
#define NEOQWERTZ3_60_R5_RCTL KC_RCTL

// Ebene 4 hat eine besondere SPACE/RALT-Wahl, wie bei dir vorgesehen:
#define NEOQWERTZ4_60_R5_LCTL KC_LCTL
#define NEOQWERTZ4_60_R5_LALT KC_LALT
#define NEOQWERTZ4_60_R5_SPACE KC_P0
#define NEOQWERTZ4_60_R5_RALT KC_RALT
#define NEOQWERTZ4_60_R5_RCTL KC_RCTL
