#pragma once
#include "layout_core.h"
// clang-format off
// Ebene 1
#define NOTED1_60_ROW1  SYS_ESC, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, DE_MINS, DE_ACUT, KC_BSPC,
#define NOTED1_60_ROW2  KC_TAB,  DE_Z, DE_Y, KC_U, KC_A, KC_Q, KC_P, KC_B, KC_M, KC_L, KC_F, KC_J, DE_SS,
#define NOTED1_60_ROW3  TD(TD_CAPS_NOTED_LEAD), KC_C, KC_S, KC_I, KC_E, KC_O, KC_D, KC_T, KC_N, KC_R, KC_H, TD(TD_NOTED_L3MO_LEAD), DE_ACUT, KC_ENT,
#define NOTED1_60_ROW4  NOTED_SHIFT, L4_MO_NOTED, KC_V, KC_X, DE_UDIA, DE_ADIA, DE_ODIA, KC_W, KC_G, DE_COMM, DE_DOT, KC_K, NOTED_SHIFT,

// Ebene 2
#define NOTED2_60_ROW1  KC_TRNS, DE_DEG, DE_SECT, UC(0x2113), UC(0x00BB), UC(0x00AB), DE_DLR, RALT(KC_E), UC(0x201E), UC(0x201C), UC(0x201D), UC(0x1E9E), DE_GRV, KC_BSPC,
#define NOTED2_60_ROW2  KC_TAB,  S(DE_Z), S(DE_Y), S(KC_U), S(KC_A), S(KC_Q), S(KC_P), S(KC_B), S(KC_M), S(KC_L), S(KC_F), S(KC_J), DE_SS,
#define NOTED2_60_ROW3  TD(TD_CAPS_NOTED_LEAD), S(KC_C), S(KC_S), S(KC_I), S(KC_E), S(KC_O), S(KC_D), S(KC_T), S(KC_N), S(KC_R), S(KC_H), TD(TD_NOTED_L3MO_LEAD), DE_ACUT, KC_ENT,
#define NOTED2_60_ROW4  NOTED_SHIFT, L4_MO_NOTED, S(KC_V), S(KC_X), S(DE_UDIA), S(DE_ADIA), S(DE_ODIA), S(KC_W), S(KC_G), DE_MINS, KC_DOT, S(KC_K), NOTED_SHIFT,

// Ebene 3
#define NOTED3_60_ROW1  UC(0x21BB), UC(0x00B9), UC(0x00B2), UC(0x00B3), UC(0x203A), UC(0x2039), UC(0x00A2), UC(0x00A5), UC(0x201A), UC(0x2018), UC(0x2019), DE_MINS, UC(0x00B7), KC_DEL,
#define NOTED3_60_ROW2  KC_NO, DE_AT, DE_UNDS, DE_LBRC, DE_RBRC, DE_CIRC, DE_EXLM, DE_LABK, DE_RABK, DE_EQL, DE_AMPR, DE_AT, DE_TILD,
#define NOTED3_60_ROW3  TD(TD_CAPS_NOTED_LEAD), DE_BSLS, DE_SLSH, DE_LCBR, DE_RCBR, DE_ASTR, DE_QUES, DE_LPRN, DE_RPRN, DE_MINS, DE_COLN, TD(TD_NOTED_L3MO_LEAD), DE_AT, KC_ENT,
#define NOTED3_60_ROW4  KC_LSFT, L4_MO_NOTED, DE_HASH, DE_DLR, DE_PIPE, DE_TILD, DE_GRV, DE_PLUS, DE_PERC, DE_DQUO, DE_QUOT, DE_SCLN, KC_RSFT,

// Ebene 4
#define NOTED4_60_ROW1  SYS_ESC, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, KC_INS,
#define NOTED4_60_ROW2  KC_TAB,  KC_ESC, KC_HOME, KC_UP, KC_END, KC_PGUP, KC_PSCR, KC_INS, KC_DEL, KC_LEFT, KC_DOWN, KC_RGHT, KC_PAUS,
#define NOTED4_60_ROW3  SYS_ESC, KC_CALC, KC_MPRV, KC_MPLY, KC_MNXT, KC_MUTE, KC_VOLD, KC_VOLU, KC_PSCR, KC_SCRL, KC_PAUS, KC_BSPC, KC_TAB, KC_ENT,
#define NOTED4_60_ROW4  KC_LSFT, KC_NUM, KC_PSLS, KC_P7, KC_P8, KC_P9, KC_PPLS, L3_MO_NOTED, KC_P4, KC_P5, KC_P6, KC_RSFT, KC_UP,
// clang-format on

#define NOTED1_60_R5_LCTL KC_LCTL
#define NOTED1_60_R5_LALT KC_LALT
#define NOTED1_60_R5_SPACE SP_FN
#define NOTED1_60_R5_RALT L4_MO_NOTED
#define NOTED1_60_R5_RCTL KC_RCTL

#define NOTED2_60_R5_LCTL KC_LCTL
#define NOTED2_60_R5_LALT KC_LALT
#define NOTED2_60_R5_SPACE SP_FN
#define NOTED2_60_R5_RALT L4_MO_NOTED
#define NOTED2_60_R5_RCTL KC_RCTL

#define NOTED3_60_R5_LCTL KC_LCTL
#define NOTED3_60_R5_LALT KC_LALT
#define NOTED3_60_R5_SPACE SP_FN
#define NOTED3_60_R5_RALT KC_RALT
#define NOTED3_60_R5_RCTL KC_RCTL

#define NOTED4_60_R5_LCTL KC_LCTL
#define NOTED4_60_R5_LALT KC_LALT
#define NOTED4_60_R5_SPACE SP_FN
#define NOTED4_60_R5_RALT KC_RALT
#define NOTED4_60_R5_RCTL KC_RCTL
