#pragma once
#include "layout_core.h"
// clang-format off
#define RGB60_ROW1  KC_ESC, QK_RGB_MATRIX_TOGGLE, QK_RGB_MATRIX_MODE_NEXT, QK_RGB_MATRIX_MODE_PREVIOUS, QK_RGB_MATRIX_VALUE_UP, QK_RGB_MATRIX_VALUE_DOWN, QK_RGB_MATRIX_SPEED_UP, QK_RGB_MATRIX_SPEED_DOWN, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_BSPC,
#define RGB60_ROW2  KC_TAB, QK_RGB_MATRIX_HUE_UP, QK_RGB_MATRIX_HUE_DOWN, QK_RGB_MATRIX_SATURATION_UP, QK_RGB_MATRIX_SATURATION_DOWN, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
#define RGB60_ROW3  KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_ENT,
#define RGB60_ROW4  KC_LSFT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_RSFT,
// clang-format on

#define RGB60_R5_LCTL KC_LCTL
#define RGB60_R5_LALT KC_LALT
#define RGB60_R5_SPACE SP_FN
#define RGB60_R5_RALT KC_NO
#define RGB60_R5_RCTL KC_RCTL
