#pragma once
#include "layout_core.h"
// clang-format off
#define SYS60_ROW1  KC_ESC, QK_BOOT, EE_CLR, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_BSPC,
#define SYS60_ROW2  KC_TAB, DF(_QWERTZ), DF(_NEOQWERTZ1), DF(_NOTED1), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
#define SYS60_ROW3  KC_CAPS, UC_MODE_CYCLE, UC_SET_LNX, UC_SET_WIN, UC_SET_WINC, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_ENT,
#define SYS60_ROW4  KC_LSFT, KC_OS_CYCLE, KC_OS_WIN, KC_OS_LNX, KC_OS_MAC, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_RSFT,
// clang-format on

#define SYS60_R5_LCTL KC_LCTL
#define SYS60_R5_LALT KC_LALT
#define SYS60_R5_SPACE SP_FN
#define SYS60_R5_RALT KC_NO
#define SYS60_R5_RCTL KC_RCTL
