#undef DYNAMIC_KEYMAP_LAYER_COUNT
#define DYNAMIC_KEYMAP_LAYER_COUNT 12 // VIA soll Layer nicht ändern

#undef DYNAMIC_KEYMAP_MACRO_COUNT
#define DYNAMIC_KEYMAP_MACRO_COUNT 8 // oder 6/4, je nach EEPROM

#ifndef DYNAMIC_KEYMAP_MACRO_MAX_LENGTH
#define DYNAMIC_KEYMAP_MACRO_MAX_LENGTH 40 // bei Bedarf 32
#endif

#ifndef VIA_EEPROM_LAYOUT_OPTIONS_SIZE
#define VIA_EEPROM_LAYOUT_OPTIONS_SIZE 0
#endif

#ifdef DYNAMIC_MACRO_SIZE
#undef DYNAMIC_MACRO_SIZE
#endif
#define DYNAMIC_MACRO_SIZE 0
